import type { CatalogAsset } from "@/lib/types";

export const demoAssets: CatalogAsset[] = [
  {
    id: "demo-live-1",
    kind: "live",
    title: "WIVA Live Demo",
    description: "قناة HLS عامة لاختبار المشغّل وتدفق الجودة المتكيّف.",
    category: "تجريبي",
    artworkUrl: "",
    backdropUrl: "",
    year: null,
    rating: null,
    quality: "Adaptive",
    language: "متعدد",
    isFeatured: true,
    isActive: true,
    demoPlaybackUrl: "https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8",
  },
  {
    id: "demo-live-2",
    kind: "live",
    title: "WIVA Sports Max 1",
    description: "مكان مخصص لقناة رياضية مرخّصة عند ربط بوابة الوسائط.",
    category: "رياضة",
    artworkUrl: "",
    backdropUrl: "",
    year: null,
    rating: null,
    quality: "FHD",
    language: "العربية",
    isFeatured: true,
    isActive: false,
  },
  {
    id: "demo-live-3",
    kind: "live",
    title: "WIVA Sports Max 2",
    description: "قناة نموذجية غير مفعّلة حتى إضافة مصدر مرخّص.",
    category: "رياضة",
    artworkUrl: "",
    backdropUrl: "",
    year: null,
    rating: null,
    quality: "4K",
    language: "العربية",
    isFeatured: false,
    isActive: false,
  },
  {
    id: "demo-movie-1",
    kind: "movie",
    title: "رحلة إلى الضوء",
    description: "بطاقة توضيحية لمكتبة الأفلام في WIVA Cloud.",
    category: "خيال علمي",
    artworkUrl: "",
    backdropUrl: "",
    year: 2026,
    rating: 8.6,
    quality: "4K",
    language: "العربية",
    isFeatured: true,
    isActive: false,
  },
  {
    id: "demo-movie-2",
    kind: "movie",
    title: "آخر محطة",
    description: "نموذج لفيلم مرخّص يظهر بعد مزامنة بوابة الوسائط.",
    category: "دراما",
    artworkUrl: "",
    backdropUrl: "",
    year: 2025,
    rating: 7.9,
    quality: "FHD",
    language: "العربية",
    isFeatured: false,
    isActive: false,
  },
  {
    id: "demo-series-1",
    kind: "series",
    title: "مدينة الغد",
    description: "نموذج لسلسلة حلقات مع تقدم مشاهدة وحفظ السجل.",
    category: "مسلسلات",
    artworkUrl: "",
    backdropUrl: "",
    year: 2026,
    rating: 8.1,
    quality: "FHD",
    language: "العربية",
    isFeatured: true,
    isActive: false,
  },
];
