const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8');
const controls = read('webui/src/components/WivaPlayerControls.tsx');
const frame = read('webui/src/components/WivaMediaPlayer.tsx');
const live = read('webui/src/screens/viewer/WatchChannel.tsx');
const media = read('webui/src/screens/viewer/WatchMedia.tsx');
const styles = read('webui/src/styles/layouts.css');
const viewerUtils = read('webui/src/screens/viewer/viewer-utils.ts');
const viewerLayout = read('webui/src/components/ViewerLayout.tsx');
const libraryFolders = read('webui/src/screens/viewer/LibraryFolders.tsx');
const adminLibrary = read('webui/src/screens/admin/LibrarySources.tsx');
const broadcaster = read('server/broadcaster.html');
const appShell = read('main.cjs');
const wivaApp = read('webui/src/components/WivaApp.tsx');

assert.doesNotMatch(live, /PlayerFitToolbar|live-player-video-(?:fit|fill|zoom)/);
assert.doesNotMatch(media, /MediaFitToolbar|media-player-video-(?:fit|fill|zoom)/);
assert.doesNotMatch(`${live}\n${media}`, />\s*(?:كامل|ملء|تقريب)\s*</);
assert.match(frame, /mode:\s*"live"\s*\|\s*"vod"/);
assert.match(frame, /is-blocked/);
assert.match(styles, /\.wiva-player\.is-blocked \.wiva-player-controls/);
assert.match(styles, /\.wiva-player\s*\{[\s\S]*?aspect-ratio:\s*16\s*\/\s*9/);
assert.match(styles, /\.wiva-player[\s\S]*?object-fit:\s*contain/);
assert.match(styles, /\.wiva-player:fullscreen[\s\S]*?width:\s*100vw\s*!important/);
assert.match(styles, /\.wiva-player:fullscreen[\s\S]*?height:\s*100vh\s*!important/);
assert.match(styles, /\.wiva-player\[data-rotation="90"\][\s\S]*?width:\s*100dvh/, 'rotated mobile video uses swapped viewport dimensions');
assert.match(styles, /body\.wiva-player-fullscreen-open main[\s\S]*?transform:\s*none\s*!important/, 'pseudo fullscreen escapes page transition containment');
assert.match(styles, /body\.wiva-player-fullscreen-open main[\s\S]*?animation:\s*none\s*!important/, 'pseudo fullscreen disables the page transition containing block');
assert.match(styles, /body\.wiva-player-fullscreen-open \.player-stage[\s\S]*?isolation:\s*auto/, 'pseudo fullscreen rises above viewer navigation');
assert.match(controls, /requestFullscreen/);
assert.match(controls, /RotateCw/);
assert.match(controls, /orientation\.lock\("landscape"\)/, 'mobile fullscreen attempts native landscape orientation');
assert.match(controls, /is-pseudo-fullscreen/, 'mobile player retains custom controls when native fullscreen is unavailable');
assert.match(controls, /applyRotation\(90\)/, 'mobile player has a CSS rotation fallback');
assert.match(controls, /dblclick/);
assert.match(controls, /key === "f"/);
assert.match(controls, /pictureInPictureEnabled/);
assert.match(controls, /wiva-player-volume/);
assert.match(controls, /setTimeout\([\s\S]*?3000/);
assert.match(controls, /\(hover: hover\) and \(pointer: fine\)/);
assert.match(controls, /video\.muted = false/);
assert.match(controls, /video\.currentTime[\s\S]*?side \* 10/);
assert.match(controls, /wiva-player-seek-feedback/);
assert.doesNotMatch(controls, /getItem\("wiva-player-muted"\)/);
assert.match(styles, /@media \(hover: none\), \(pointer: coarse\)/);
assert.match(viewerUtils, /Mux\\s\+HLS\\s\+Test/i);
assert.match(viewerUtils, /تلقائية/);
assert.match(live, /15_000/);
assert.match(live, /استغرق تشغيل البث وقتًا أطول من المعتاد/);
assert.match(live, /MANIFEST_PARSED[\s\S]*?media\.play\(\)/);
assert.match(live, /function markPlaying\(\)[\s\S]*?clearTimeout\(recoveryTimer\)[\s\S]*?setStarted\(true\)/);
assert.match(live, /playError instanceof DOMException[\s\S]*?NotAllowedError[\s\S]*?clearStartupTimer\(\)[\s\S]*?setStarted\(true\)/);
assert.match(live, /startLevel:\s*0/);
assert.match(live, /capLevelToPlayerSize:\s*true/);
assert.match(live, /abrEwmaDefaultEstimate:\s*500_000/);
assert.match(live, /abrEwmaSlowLive:\s*18/, 'IPTV automatic quality uses a stable long bandwidth estimate');
assert.match(live, /abrBandWidthUpFactor:\s*0\.6/, 'IPTV automatic quality upgrades conservatively to avoid oscillation');
assert.match(live, /lowLatencyMode:\s*false/, 'ordinary IPTV uses a resilience-first HLS buffer');
assert.match(live, /maxBufferLength:\s*45/, 'IPTV keeps enough forward buffer to absorb provider jitter');
assert.match(live, /maxBufferHole:\s*0\.75/, 'small IPTV timestamp gaps do not stall playback');
assert.match(live, /startLoad\?\.\(-1\)/, 'IPTV playback restarts loading after a sustained stall');
assert.match(live, /hlsScriptPromise\s*=\s*null[\s\S]*?throw error/, 'HLS player asset can recover after an initial load failure');
assert.match(live, /manifestLoadingTimeOut:\s*12000/, 'IPTV manifest loading fails clearly instead of waiting indefinitely');
assert.match(live, /fragLoadingMaxRetry:\s*6/, 'IPTV segment retries remain bounded but tolerate brief provider loss');
assert.match(media, /position\s*-\s*10/, 'resume starts ten seconds before the saved position');
assert.match(media, /\?download=1/, 'viewer download actions use the controlled download endpoint');
assert.doesNotMatch(viewerLayout, /to:\s*["']\/search["']/, 'search is not duplicated in desktop or mobile navigation');
assert.match(styles, /\.mobile-bottom-nav[\s\S]*?grid-template-columns:\s*repeat\(4,\s*1fr\)/, 'mobile navigation uses four balanced columns');
assert.match(libraryFolders, /permissions\?\.manageLibrary/, 'folder upload controls require an authenticated admin session');
assert.match(libraryFolders, /\.pdf,\.epub/, 'admin folder uploads include books and documents');
assert.match(adminLibrary, /updateLibraryPolicy/, 'library download policy is managed from the admin dashboard');
assert.doesNotMatch(broadcaster, /track\.onmute\s*=\s*\(\)\s*=>\s*scheduleAudioRestart/, 'transient HDMI mute does not restart capture');
assert.doesNotMatch(broadcaster, /track\.enabled\s*!==\s*false\s*&&\s*!track\.muted/, 'live HDMI audio remains healthy during transient mute');
assert.match(broadcaster, /AUDIO_MISSING_RESTART_MS\s*=\s*20000/, 'missing capture audio uses a sustained grace period');
assert.match(broadcaster, /AUDIO_STALL_RESTART_MS\s*=\s*20000/, 'persistently muted HDMI audio recovers after a sustained grace period');
assert.match(broadcaster, /navigator\.hardwareConcurrency/, 'capture load protection adapts to the Windows host hardware');
assert.match(broadcaster, /CAPTURE_CAPACITY\.heavyAt/, 'capture sender load uses a hardware-aware heavy-viewer threshold');
assert.match(broadcaster, /CAPTURE_CAPACITY\.crowdedRecoveryAt/, 'capture capacity uses a lower recovery threshold to prevent quality oscillation');
assert.match(broadcaster, /scheduleCapacityRetune\(\)/, 'capture senders are retuned when viewer load changes');
assert.match(live, /pcRef\.current\s*!==\s*pc/, 'stale WebRTC peer events cannot trigger reconnect loops');
assert.doesNotMatch(live, /track\.onmute[\s\S]{0,240}scheduleReconnect/, 'viewer does not rebuild video for a transient audio mute');
assert.match(live, /weakQualitySamples\s*>=\s*2/, 'automatic capture quality requires repeated weak samples before degrading');
assert.match(live, /stableQualitySamples\s*>=\s*6/, 'automatic capture quality waits for sustained stability before upgrading');
assert.match(live, /framesDropped/, 'automatic capture quality observes decoder frame drops');
assert.match(live, /freezeCount/, 'automatic capture quality observes playback freezes');
assert.match(live, /jitterBufferTarget/, 'capture playback keeps a small jitter safety buffer');
assert.match(live, /playoutDelayHint/, 'capture playback asks the browser for stable playout timing');
assert.match(live, /45_000/, 'automatic capture quality has a recovery cooldown');
assert.match(appShell, /show:\s*false[\s\S]*?ready-to-show/, 'agent window stays hidden until its renderer is ready');
assert.match(appShell, /recoverBroadcaster[\s\S]*?render-process-gone/, 'capture renderer crashes recover without restarting WIVA');
assert.match(wivaApp, /import \{ Live \} from "@\/screens\/viewer\/Live"/, 'primary live route is included in the initial viewer bundle');

console.log('WIVA unified player UI tests passed');
