import Link from "next/link";
import { AlertCircle, Clapperboard, CreditCard, EyeOff, Radio, ServerCog, ShieldCheck, TriangleAlert, UsersRound } from "lucide-react";
import { dashboardCounts } from "@/lib/db";
import { databaseConfigured, isDemoMode } from "@/lib/env";
import { requireAdminPage } from "@/lib/auth";

export default async function AdminDashboard() {
  await requireAdminPage();
  const counts = await dashboardCounts();
  return <><header className="admin-page-heading"><div><h1>نظرة عامة</h1><p>ما يحتاج انتباهك الآن، ثم حالة المنصة.</p></div></header>{!databaseConfigured() ? <div className="notice-banner"><TriangleAlert size={19} /><span>{isDemoMode() ? "المنصة تعمل بوضع العرض، لذلك لا يمكن حفظ تغييرات حقيقية الآن." : "التخزين غير جاهز الآن؛ أوقفنا التشغيل لحماية بيانات المنصة."}</span></div> : null}<section className="stats-grid"><div className="stat-card"><span><Clapperboard /></span><strong>{counts.assets}</strong><small>إجمالي العناصر</small></div><div className="stat-card"><span><Radio /></span><strong>{counts.live}</strong><small>قنوات مباشرة</small></div><div className="stat-card"><span><ServerCog /></span><strong>{counts.activeProviders}/{counts.providers}</strong><small>مزوّدون نشطون</small></div><div className="stat-card"><span><UsersRound /></span><strong>{counts.viewers}</strong><small>حسابات مشاهدين</small></div></section><section className="architecture-card action-queue"><div className="ops-card-heading"><div><ShieldCheck /><span><h2>قائمة العمل</h2><p>ابدأ بالأعلى تأثيرًا على المشاهدين.</p></span></div></div><div className="admin-action-list"><Link href="/admin/channels"><span><AlertCircle /></span><div><strong>مراجعة سلامة المحتوى</strong><small>عناصر حساسة أو معلومات ليست فيديو</small></div><b>{counts.needsReview}</b></Link><Link href="/admin/viewers"><span><CreditCard /></span><div><strong>طلبات التجديد</strong><small>طلبات تنتظر الموافقة أو الرفض</small></div><b>{counts.pendingPayments}</b></Link><Link href="/admin/channels"><span><EyeOff /></span><div><strong>المحتوى المتوقف</strong><small>مستورد لكنه غير ظاهر للمشاهدين</small></div><b>{counts.hiddenAssets}</b></Link><Link href="/admin/providers"><span><ServerCog /></span><div><strong>حالة المزوّدين</strong><small>تحقق من المصادر المتوقفة أو المتدهورة</small></div><b>{Math.max(0, counts.providers - counts.activeProviders)}</b></Link></div></section></>;
}
