/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchIdRouteImport } from './routes/watch.$id'
import { Route as LoginAdminRouteImport } from './routes/login.admin'
import { Route as AdminTickersRouteImport } from './routes/admin.tickers'
import { Route as AdminThemesRouteImport } from './routes/admin.themes'
import { Route as AdminReleasesRouteImport } from './routes/admin.releases'
import { Route as AdminPathsRouteImport } from './routes/admin.paths'
import { Route as AdminNetworksRouteImport } from './routes/admin.networks'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminLicensesRouteImport } from './routes/admin.licenses'
import { Route as AdminIptvRouteImport } from './routes/admin.iptv'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as ApiPublicDeviceStateRouteImport } from './routes/api/public/device-state'
import { Route as ApiPublicLicenseVerifyRouteImport } from './routes/api/public/license.verify'
import { Route as ApiPublicIptvListRouteImport } from './routes/api/public/iptv.list'
import { Route as ApiPublicDownloadFileRouteImport } from './routes/api.public.download.$file'

const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/login/admin',
  path: '/login/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTickersRoute = AdminTickersRouteImport.update({
  id: '/tickers',
  path: '/tickers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminThemesRoute = AdminThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReleasesRoute = AdminReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPathsRoute = AdminPathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNetworksRoute = AdminNetworksRouteImport.update({
  id: '/networks',
  path: '/networks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLicensesRoute = AdminLicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIptvRoute = AdminIptvRouteImport.update({
  id: '/iptv',
  path: '/iptv',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicDeviceStateRoute = ApiPublicDeviceStateRouteImport.update({
  id: '/api/public/device-state',
  path: '/api/public/device-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLicenseVerifyRoute = ApiPublicLicenseVerifyRouteImport.update({
  id: '/api/public/license/verify',
  path: '/api/public/license/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIptvListRoute = ApiPublicIptvListRouteImport.update({
  id: '/api/public/iptv/list',
  path: '/api/public/iptv/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDownloadFileRoute = ApiPublicDownloadFileRouteImport.update({
  id: '/api/public/download/$file',
  path: '/api/public/download/$file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/library': typeof LibraryRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/iptv': typeof AdminIptvRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/networks': typeof AdminNetworksRoute
  '/admin/paths': typeof AdminPathsRoute
  '/admin/releases': typeof AdminReleasesRoute
  '/admin/themes': typeof AdminThemesRoute
  '/admin/tickers': typeof AdminTickersRoute
  '/login/admin': typeof LoginAdminRoute
  '/watch/$id': typeof WatchIdRoute
  '/api/public/device-state': typeof ApiPublicDeviceStateRoute
  '/api/public/download/$file': typeof ApiPublicDownloadFileRoute
  '/api/public/iptv/list': typeof ApiPublicIptvListRoute
  '/api/public/license/verify': typeof ApiPublicLicenseVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/library': typeof LibraryRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/iptv': typeof AdminIptvRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/networks': typeof AdminNetworksRoute
  '/admin/paths': typeof AdminPathsRoute
  '/admin/releases': typeof AdminReleasesRoute
  '/admin/themes': typeof AdminThemesRoute
  '/admin/tickers': typeof AdminTickersRoute
  '/login/admin': typeof LoginAdminRoute
  '/watch/$id': typeof WatchIdRoute
  '/api/public/device-state': typeof ApiPublicDeviceStateRoute
  '/api/public/download/$file': typeof ApiPublicDownloadFileRoute
  '/api/public/iptv/list': typeof ApiPublicIptvListRoute
  '/api/public/license/verify': typeof ApiPublicLicenseVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/library': typeof LibraryRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/iptv': typeof AdminIptvRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/networks': typeof AdminNetworksRoute
  '/admin/paths': typeof AdminPathsRoute
  '/admin/releases': typeof AdminReleasesRoute
  '/admin/themes': typeof AdminThemesRoute
  '/admin/tickers': typeof AdminTickersRoute
  '/login/admin': typeof LoginAdminRoute
  '/watch/$id': typeof WatchIdRoute
  '/api/public/device-state': typeof ApiPublicDeviceStateRoute
  '/api/public/download/$file': typeof ApiPublicDownloadFileRoute
  '/api/public/iptv/list': typeof ApiPublicIptvListRoute
  '/api/public/license/verify': typeof ApiPublicLicenseVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/favorites'
    | '/library'
    | '/admin/categories'
    | '/admin/iptv'
    | '/admin/licenses'
    | '/admin/messages'
    | '/admin/networks'
    | '/admin/paths'
    | '/admin/releases'
    | '/admin/themes'
    | '/admin/tickers'
    | '/login/admin'
    | '/watch/$id'
    | '/api/public/device-state'
    | '/api/public/download/$file'
    | '/api/public/iptv/list'
    | '/api/public/license/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/favorites'
    | '/library'
    | '/admin/categories'
    | '/admin/iptv'
    | '/admin/licenses'
    | '/admin/messages'
    | '/admin/networks'
    | '/admin/paths'
    | '/admin/releases'
    | '/admin/themes'
    | '/admin/tickers'
    | '/login/admin'
    | '/watch/$id'
    | '/api/public/device-state'
    | '/api/public/download/$file'
    | '/api/public/iptv/list'
    | '/api/public/license/verify'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/favorites'
    | '/library'
    | '/admin/categories'
    | '/admin/iptv'
    | '/admin/licenses'
    | '/admin/messages'
    | '/admin/networks'
    | '/admin/paths'
    | '/admin/releases'
    | '/admin/themes'
    | '/admin/tickers'
    | '/login/admin'
    | '/watch/$id'
    | '/api/public/device-state'
    | '/api/public/download/$file'
    | '/api/public/iptv/list'
    | '/api/public/license/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FavoritesRoute: typeof FavoritesRoute
  LibraryRoute: typeof LibraryRoute
  LoginAdminRoute: typeof LoginAdminRoute
  WatchIdRoute: typeof WatchIdRoute
  ApiPublicDeviceStateRoute: typeof ApiPublicDeviceStateRoute
  ApiPublicDownloadFileRoute: typeof ApiPublicDownloadFileRoute
  ApiPublicIptvListRoute: typeof ApiPublicIptvListRoute
  ApiPublicLicenseVerifyRoute: typeof ApiPublicLicenseVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/admin': {
      id: '/login/admin'
      path: '/login/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tickers': {
      id: '/admin/tickers'
      path: '/tickers'
      fullPath: '/admin/tickers'
      preLoaderRoute: typeof AdminTickersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/themes': {
      id: '/admin/themes'
      path: '/themes'
      fullPath: '/admin/themes'
      preLoaderRoute: typeof AdminThemesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/releases': {
      id: '/admin/releases'
      path: '/releases'
      fullPath: '/admin/releases'
      preLoaderRoute: typeof AdminReleasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paths': {
      id: '/admin/paths'
      path: '/paths'
      fullPath: '/admin/paths'
      preLoaderRoute: typeof AdminPathsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/networks': {
      id: '/admin/networks'
      path: '/networks'
      fullPath: '/admin/networks'
      preLoaderRoute: typeof AdminNetworksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/licenses': {
      id: '/admin/licenses'
      path: '/licenses'
      fullPath: '/admin/licenses'
      preLoaderRoute: typeof AdminLicensesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/iptv': {
      id: '/admin/iptv'
      path: '/iptv'
      fullPath: '/admin/iptv'
      preLoaderRoute: typeof AdminIptvRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/device-state': {
      id: '/api/public/device-state'
      path: '/api/public/device-state'
      fullPath: '/api/public/device-state'
      preLoaderRoute: typeof ApiPublicDeviceStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license/verify': {
      id: '/api/public/license/verify'
      path: '/api/public/license/verify'
      fullPath: '/api/public/license/verify'
      preLoaderRoute: typeof ApiPublicLicenseVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/iptv/list': {
      id: '/api/public/iptv/list'
      path: '/api/public/iptv/list'
      fullPath: '/api/public/iptv/list'
      preLoaderRoute: typeof ApiPublicIptvListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/download/$file': {
      id: '/api/public/download/$file'
      path: '/api/public/download/$file'
      fullPath: '/api/public/download/$file'
      preLoaderRoute: typeof ApiPublicDownloadFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminIptvRoute: typeof AdminIptvRoute
  AdminLicensesRoute: typeof AdminLicensesRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNetworksRoute: typeof AdminNetworksRoute
  AdminPathsRoute: typeof AdminPathsRoute
  AdminReleasesRoute: typeof AdminReleasesRoute
  AdminThemesRoute: typeof AdminThemesRoute
  AdminTickersRoute: typeof AdminTickersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminIptvRoute: AdminIptvRoute,
  AdminLicensesRoute: AdminLicensesRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNetworksRoute: AdminNetworksRoute,
  AdminPathsRoute: AdminPathsRoute,
  AdminReleasesRoute: AdminReleasesRoute,
  AdminThemesRoute: AdminThemesRoute,
  AdminTickersRoute: AdminTickersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FavoritesRoute: FavoritesRoute,
  LibraryRoute: LibraryRoute,
  LoginAdminRoute: LoginAdminRoute,
  WatchIdRoute: WatchIdRoute,
  ApiPublicDeviceStateRoute: ApiPublicDeviceStateRoute,
  ApiPublicDownloadFileRoute: ApiPublicDownloadFileRoute,
  ApiPublicIptvListRoute: ApiPublicIptvListRoute,
  ApiPublicLicenseVerifyRoute: ApiPublicLicenseVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
